language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script: vendor/bin/phpunit -c phpunit.xml.dist --coverage-text
